name: Hello
on: [push, pull_request]
jobs:
 test:
   name: ansibleplaybook
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      - name: actions
      - uses: dawidd6/action-ansible-playbook@v2
      - name: run ansible playbook
        run: ansible-playbook playbook.yaml
