name: Hello
on: [push, pull_request]
jobs:
 test:
   name: ansibleplaybook
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      - name: actions
        run: ansible-playbook playbook.yaml
